Afluex/Controllers/blogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Afluex.Controllers
{
    public class blogController : Controller
    {
        // GET: blog
        public ActionResult Index()
        {
            return View();
        }

        [ActionName("10-Benefits-of-Hiring-Outdoor-Advertising-Agencies-for-your-business")]
        public ActionResult outdoor_advertising()
        {
            return View("outdoor_advertising");
        }
    }
}

Afluex/Controllers/webController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using CaptchaMvc.HtmlHelpers;
using System.Web.Mvc;
using Afluex.Models;
using System.Data;
using Afluex.Filter;
using PagedList;
using System.IO;

namespace Afluex.Controllers
{
    public class webController : Controller
    {
        // GET: web
        [ActionName("software-development")]
        public ActionResult it_services()
        {
            return View("it_services");
        }
        [ActionName("company-overview")]
        public ActionResult company_overview()
        {
            return View("company_overview");
        }
        [ActionName("vision-and-mission")]
        public ActionResult vision_and_mission()
        {
            return View("vision_and_mission");
        }
        [ActionName("our-team")]
        public ActionResult our_team()
        {
            return View("our_team");
        }
        // [ActionName("website-development-services")]
        [ActionName("website-development-company")]
        public ActionResult website_development_services()
        {
            return View("website_development_services");

        }
        //[ActionName("app-development-services")]
        [ActionName("mobile-app-development-company")]
        public ActionResult Mobile_Development()
        {
            return View("Mobile_Development");
        }
        //[ActionName("software-development-services")]
        [ActionName("software-development-company")]
        public ActionResult software_development_services()
        {
            return View("software_development_services");
        }
        //[ActionName("mvc-training-services")]
        [ActionName("mvc-training")]
        public ActionResult mvc_training_services()
        {
            return View("mvc_training_services");
        }
        //[ActionName("digital-marketing-services")]
        [ActionName("digital-marketing-company")]
        public ActionResult digital_marketing_services()
        {
            return View("digital_marketing_services");
        }
        //[ActionName("domain-and-hosting-services")]
        [ActionName("domain-and-hosting")]
        public ActionResult domain_hosting_services()
        {
            return View("domain_hosting_services");
        }
        //[ActionName("seo-services")]
        [ActionName("seo-agency")]
        public ActionResult seo_services()
        {
            return View("seo_services");
        }
        [ActionName("graphic-design-company")]
        public ActionResult graphic_designs()
        {
            return View("graphic_designs");
        }
        [ActionName("mlm-software-development-company")]
        public ActionResult mlm_software()
        {
            return View("mlm_software");
        }
        [ActionName("real-estate-software-company")]
        public ActionResult real_estate_software()
        {
            return View("real_estate_software");
        }
        [ActionName("ecommerce-software-development")]
        public ActionResult ecommerce_software()
        {
            return View("ecommerce_software");
        }
        [ActionName("School-Management")]
        public ActionResult School_Management()
        {
            return View("School_Management");
        }
        [ActionName("travel-portal-software")]
        public ActionResult travel_portal_software()
        {
            return View("travel_portal_software");
        }
        [ActionName("flight-booking-software")]
        public ActionResult flight_booking_software()
        {
            return View("flight_booking_software");
        }
        [ActionName("hospital-management-software")]
        public ActionResult hospital_management_software()
        {
            return View("hospital_management_software");
        }
        [ActionName("mobile-recharge-software-development")]
        public ActionResult mobile_recharge_software()
        {
            return View("mobile_recharge_software");
        }
        [ActionName("news-portal-software-development")]
        public ActionResult news_portal_software()
        {
            return View("news_portal_software");
        }
        [ActionName("crm-software-development-company")]
        public ActionResult crm_software()
        {
            return View("crm_software");
        }
        [ActionName("hris-hrms-software-development")]
        public ActionResult hrms_software()
        {
            return View("hrms_software");
        }
        [ActionName("erp-software-development")]
        public ActionResult erp_software()
        {
            return View("erp_software");
        }
        [ActionName("followup-software-development")]
        public ActionResult followup_software()
        {
            return View("followup_software");
        }
        [ActionName("daily-expenses-software")]
        public ActionResult daily_expenses_software()
        {
            return View("daily_expenses_software");
        }
        [ActionName("nidhi-software-development")]
        public ActionResult nidhi_software()
        {
            return View("nidhi_software");
        }
        [ActionName("helping-software-development")]
        public ActionResult helping_software()
        {
            return View("helping_software");
        }
        [ActionName("restaurant-software-development")]
        public ActionResult restaurant_billing_software()
        {
            return View("restaurant_billing_software");
        }
        [ActionName("loan-management-software-development")]
        public ActionResult loan_management_software()
        {
            return View("loan_management_software");
        }
        [ActionName("mart-billing-software-development")]
        public ActionResult mart_billing_software()
        {
            return View("mart_billing_software");
        }
        [ActionName("inventory-management-software-development")]
        public ActionResult inventry_management_software()
        {
            return View("inventry_management_software");
        }

        [ActionName("privacy-policy")]
        public ActionResult privacy_policy()
        {
            return View("privacy_policy");
        }

        public ActionResult portfolio()
        {
            return View("portfolio");
        }

        public ActionResult gallery()
        {
            return View("gallery");
        }
        [ActionName("school-management-software")]
        public ActionResult Edu_tech()
        {
            return View("Edu_tech");
        }

        #region blog
        public ActionResult blog(string id)
        {

            Blog obj = new Blog();
            if (id != null && id != "")
            {
                obj.Fk_CategoryId = id;
            }

            List<Blog> lst = new List<Blog>();
            List<Blog> lst1 = new List<Blog>();
            List<Blog> lst2 = new List<Blog>();
            List<Blog> lst3 = new List<Blog>();
            DataSet ds = obj.GetBlog();
            if (ds != null && ds.Tables[0].Rows.Count > 0)
            {

                foreach (DataRow r in ds.Tables[0].Rows)
                {
                    Blog obj1 = new Blog();
                    obj1.Pk_BlogId = r["Pk_BlogId"].ToString();
                    obj1.Title = r["Title"].ToString();
                    obj1.ShortDecription = r["ShortDecription"].ToString();
                    obj1.Decription = r["Description"].ToString();
                    obj1.FileUpload = r["AddedOn"].ToString();
                    obj1.FileName = r["Images"].ToString();
                    obj1.AddedBy = r["Name"].ToString();
                    lst.Add(obj1);
                }

                obj.List = lst;


                foreach (DataRow r in ds.Tables[2].Rows)
                {
                    Blog obj1 = new Blog();
                    obj1.Fk_CategoryId = r["CategoryName"].ToString();
                    obj1.Pk_BlogId = r["Fk_BlogId"].ToString();


                    lst2.Add(obj1);
                }

                obj.lstcategory = lst2;

            }
            if (ds != null && ds.Tables[3].Rows.Count > 0)
            {

                foreach (DataRow r in ds.Tables[3].Rows)
                {
                    Blog obj1 = new Blog();
                    obj1.Fk_CategoryId = r["PK_CategoryID"].ToString();
                    obj1.CategoryName = r["CategoryName"].ToString();
                    lst3.Add(obj1);
                }

                obj.lstcategoryfull = lst3;
            }
            return View(obj);
        }

        public ActionResult blogDetails(string id)
        {
            Blog obj = new Blog();
            if (id != null && id != "")
            {

                List<Blog> lst = new List<Blog>();
                List<Blog> lst1 = new List<Blog>();
                List<Blog> lst2 = new List<Blog>();

                obj.Pk_BlogId = id;
                DataSet ds = obj.GetBlog();
                if (ds != null && ds.Tables[0].Rows.Count > 0)
                {
                    foreach (DataRow r in ds.Tables[0].Rows)
                    {
                        Blog obj1 = new Blog();
                        obj1.Pk_BlogId = r["Pk_BlogId"].ToString();
                        obj1.Title = r["Title"].ToString();
                        obj1.ShortDecription = r["ShortDecription"].ToString();
                        obj1.Decription = r["Description"].ToString();
                        obj1.FileName = r["images"].ToString();

                        obj1.AddedBy = r["Name"].ToString();
                        lst.Add(obj1);
                    }

                    obj.List = lst;
                    foreach (DataRow r in ds.Tables[1].Rows)
                    {
                        Blog obj1 = new Blog();
                        obj1.FileName = r["Images"].ToString();

Afluex/Views/web/CompilationPage.cshtml
@{
    ViewBag.Title = "CompilationPage";
    Layout = "~/Views/Shared/Web_Layout.cshtml";
}
<link href="https://fonts.googleapis.com/css2?family=Teko:wght@600&display=swap" rel="stylesheet">
<section class="page-title text-center" style="background-image:url(../../afluexit/images/background/page_blog.jpeg);">
    <div class="container">
        <h1>Error Page</h1>
    </div>
    <!--Page Info-->
    <div class="page-info">
        <div class="container clearfix">
            <ul class="bread-crumb clearfix">
                <li><a href="/web/software-development"><i class="fa fa-home"></i></a> </li>
                <li><span><i class="fa fa-angle-right" aria-hidden="true"></i></span></li>
                <li>Error Page</li>
            </ul>
        </div>
    </div>
</section>
<!-- End Page Title -->

<section class="error-section">
    <div class="container">
        <div class="content">
            <h1 class="error_text">404</h1>
            <h2>Oops... It looks like you ‘re lost !</h2>
            <div class="text mt-3">Oops! The page you are looking for does not exist. It might have been moved or deleted.</div>
            <a href="/web/software-development" class="btn btn-lg btn-custom mt-4 text-uppercase"><i class="fa fa-home"></i> Back to home</a>
        </div>
    </div>
</section>

Afluex/Views/web/company_overview.cshtml
@{
    ViewBag.Title = "company_overview";
    Layout = "~/Views/Shared/Web_Layout.cshtml";
}

<section class="page-title text-center" style="background-image:url(../../afluexit/images/background/page_about.jpeg);">
    <div class="container">
        <h1>About Us</h1>
    </div>
    <!--Page Info-->
    <div class="page-info">
        <div class="container clearfix">
            <ul class="bread-crumb clearfix">
                <li><a href="/web/software-development"><i class="fa fa-home"></i></a> </li>
                <li><span><i class="fa fa-angle-right" aria-hidden="true"></i></span></li>
                <li>About Us</li>
                <li><span><i class="fa fa-angle-right" aria-hidden="true"></i></span></li>
                <li>Company Overview</li>
            </ul>
        </div>
    </div>
</section>
<!-- End Page Title -->

<section class="aboutus_page">
    <div class="container">
        <div class="row">
            <!-- Info Column -->
            <div class="info-column col-xl-8 col-lg-12 col-md-6 col-sm-12">
                <div class="inner-column">
                    <div class="sec-title">
                        <h2 class="title">Best Software Development Company In Lucknow</h2>
                        <h2 class="font_text">Welcome To<br> Company Overview</h2>
                    </div>

                    <p class="text-justify">
                        Welcome to Afluex Multiservices LLP, a premier software development company dedicated to
                        transforming businesses through innovative technology solutions. With our cutting-edge expertise
                        and client-centric approach, we deliver customized software solutions that drive growth, enhance
                        efficiency, and maximize ROI.
                    </p>
                    <p class="text-justify">
                        At Afluex, we understand that every business is unique, with its own set of challenges and goals.
                        That's why we take the time to listen and understand your specific requirements before designing
                        and developing tailored software solutions that address your needs effectively.
                    </p>
                    <p>
                        Our team of highly skilled software engineers, designers, and project managers are committed to
                        delivering excellence in every project we undertake. With expertise in the latest technologies and
                        industry best practices, we ensure that our solutions are at the forefront of innovation and meet the
                        highest quality standards.
                    </p>

                </div>
            </div>

            <!-- Video Column -->
            <div class="abt-column col-xl-4 col-lg-12 col-md-6 col-sm-12">
                <div class="inner-column">
                    <img src="~/afluexit/images/about_img2.jpg" class="img-fluid" alt="">
                </div>
            </div>

            <div class="info-column col-xl-12 col-lg-12 col-md-12 col-sm-12 mt-5">
                <div class="inner-column">
                    <div class="sec-title">
                        <span class="title">Our comprehensive range</span>
                        <h3>Solution to fit your needs</h3>
                    </div>

                    <p class="text-justify">
                        Our comprehensive range of software development services covers the entire development lifecycle.
                        From ideation and conceptualization to design, development, testing, deployment, and ongoing
                        support, we provide end-to-end solutions that seamlessly integrate into your existing infrastructure.
                    </p>
                    <p>
                        Whether you need web application development, mobile app development, enterprise software
                        solutions, or custom software development, we have the expertise to turn your vision into reality.
                        Our team is proficient in a wide array of technologies, including but not limited to:
                    </p>
                    <ul>
                        <li>Front-end and back-end development</li>
                        <li>Cloud computing and SaaS solutions</li>
                        <li>Database design and management</li>
                        <li>API integration and third-party systems</li>
                        <li>AI and machine learning</li>
                        <li>IoT solutions</li>
                        <li>E-commerce platforms</li>
                        <li>Quality assurance and testing</li>
                    </ul>
                    <p>
                        We pride ourselves on being a trusted technology partner for businesses across various industries,
                        including healthcare, finance, e-commerce, logistics, and more. Our track record of successful
                        projects and satisfied clients is a testament to our commitment to delivering exceptional results.
                    </p>
                    <p>
                        At Afluex, we believe that communication and collaboration are key to a successful partnership. We
                        work closely with you throughout the development process, providing regular updates and seeking
                        your feedback to ensure that the final product aligns perfectly with your expectations.
                    </p>
                    <p>
                        In addition to software development, we offer ongoing maintenance and support services to ensure
                        that your software remains up-to-date, secure, and optimized for peak performance. Our dedicated
                        support team is always available to address any issues or concerns that may arise.
                    </p>
                    <p>
                        Take your business to new heights with our innovative software solutions. Contact us today to
                        discuss your project and discover how Afluex Multiservices LLP can help you unlock your full
                        potential through technology.
                    </p>
                </div>
            </div>

            <div class="info-column col-xl-12 col-lg-12 col-md-12 col-sm-12 mt-5">
                <div class="inner-column">
                    <div class="sec-title">
                        <span class="title">Our Soldiers & Social Network</span>
                        <h3>Our Soldiers</h3>
                    </div>

                    <p class="text-justify">We have more than year’s of experience wonderful creative team who is the master of their field and they are always ready to give their best result, no matter how the circumstances are.</p>
                </div>
                <div class="inner-column">
                    <div class="sec-title">
                        <h3>Our Service Network</h3>
                    </div>

                    <p class="text-justify">We Provide our service in Utter Pradesh & Bihar, Jharkhand, Uttrakhand and other ancillary states.</p>
                </div>
            </div>
        </div>
    </div>
</section>

Afluex/Views/web/software_development_services.cshtml
@{
    ViewBag.Title = "software_development_services";
    Layout = "~/Views/Shared/Web_Layout.cshtml";
}
<section class="page-title text-center" style="background-image:url(../../afluexit/images/background/page_services.jpeg);">
    <div class="container">
        <h1>Software Development Company</h1>
    </div>
    <!--Page Info-->
    <div class="page-info">
        <div class="container clearfix">
            <ul class="bread-crumb clearfix">
                <li><a href="/web/software-development"><i class="fa fa-home"></i></a> </li>
                <li><span><i class="fa fa-angle-right" aria-hidden="true"></i></span></li>
                <li>Services</li>
                <li><span><i class="fa fa-angle-right" aria-hidden="true"></i></span></li>
                <li>Software Development</li>
            </ul>
        </div>
    </div>
</section>
<!-- End Page Title -->

<section class="services_page">
    <div class="container">
        <div class="row">
            <!-- Info Column -->
            <div class="col-xl-8 col-lg-8 col-md-8 col-sm-12">
                <div class="services_inner_column">
                    <div class="ser_title">
                        <span class="title">THE BEST PLACE TO FIND THE SOFTWARE YOU WANT</span>
                        <h2>Software Development Company In Lucknow, India</h2>
                    </div>
                    <div class="services_content_details">
                        <div class="row">
                            <div class="col-md-7 col-lg-7">
                                <p class="text-justify">
                                    Afluex Multiservices LLP is an experienced.net development company, that focuses on earning the highest level of customer satisfaction by offering the best .NET software development Company In Lucknow. There are thousands of businesses that use Microsoft’s
                                    robust Dot Net framework for efficient performance and to push the growth trajectory. This framework allows entrepreneurs and businesses to get the innovative, intuitive and effective business application for desktop
                                    and web to improve overall productivity.
                                </p>
                            </div>
                            <div class="col-md-5 col-lg-5">
                                <img src="~/afluexit/images/services/devices-bro.png" class="img-fluid" alt="software-devlopment" />
                            </div>
                        </div>
                        <p class="text-justify">
                            Afluex is a leading provider of Dot Net development services. We have employed knowledgeable ASP.NET developers who have vast experience in .NET technology. By hiring us, you can avail the best features and functionalities of a robust ASP.NET framework.
                        </p>
                        <h4 class="green">Our Software Development Services In Lucknow</h4>
                        <h5 class="green">Developing Solutions for the Future</h5>
                        <p class="mt-1 text-justify">
                            Afluex Multiservices LLP is a custom software development company in Lucknow that provides a wide range of services, including web app development, UX and UI design, mobile app development. Over the years (7+), the company has
                            implemented more than 100+ projects for startups, medium-sized businesses and enterprises. Afluex has expertise in the development of MLM software solutions, Real Estate Software, eCommerce Software and websites, various mobile
                            apps.
                        </p>
                        <h4 class="green">Different Industries We Serve...</h4>
                        <p class="text-justify">
                            The Software Industry is a big ocean where Software Services are not limited to one particular business sector. Afluex Multiservices LLP is one of the few dependable companies which has met its customer’s expectations, irrespective
                            of their business sectors. We are an acclaimed Software Development Company in India, where we develop user-friendly applications spanning a vast industrial belt-
                        </p>
                        <div class="softdevslider owl-carousel owl-theme text-center">
                            <div class="softdevslider_item">
                                <img src="~/afluexit/images/services/ser-realestate.png" class="img-fluid" alt="software-devlopment" />
                                <h6>Real Estate</h6>
                                <p>Afluex is a leading software development company that.</p>
                                <a href="#">Read More.</a>
                            </div>
                            <div class="softdevslider_item">
                                <img src="~/afluexit/images/services/connected-mlm.png" class="img-fluid" alt="software-devlopment" />
                                <h6 class="green">Multi Level Marketing</h6>
                                <p>Afluex is a big name in the MLM industry for MLM software and.</p>
                                <a href="#">Read More.</a>
                            </div>
                            <div class="softdevslider_item">
                                <img src="~/afluexit/images/services/online-shopping.png" class="img-fluid" alt="software-devlopment" />
                                <h6>Retail and E-commerce</h6>
                                <p>Afluex is a professional eCommerce software development company.</p>
                                <a href="#">Read More.</a>
                            </div>
                            <div class="softdevslider_item">
                                <img src="~/afluexit/images/services/ser-school.png" class="img-fluid" alt="software-devlopment" />
                                <h6>School Management Software</h6>
                                <p>A School management system transforms schools into smart...</p>
                                <a href="#">Read More.</a>
                            </div>
                            <div class="softdevslider_item">
                                <img src="~/afluexit/images/services/ser-inventry.png" class="img-fluid" alt="software-devlopment" />
                                <h6>Inventory Management Software</h6>
                                <p>Inventory Management Software For Growing Businesses...</p>
                                <a href="#">Read More.</a>
                            </div>
                        </div>
                        <h5 class="green">Key Benefits to choose Afluex as a Software Development Company</h5>
                        <p class="text-justify">
                            In order to gain maximum benefits from Software Development Services In Lucknow, it is vital to operate as the Best Software Development Company as well. This will save considerable time and effort and allow the parent company
                            to focus on quality and timely delivery.
                        </p>
                        <p class="text-justify">
                            Afluex has been largely successful in meeting our customer's requirements as we support companies requiring quality and quick Software Development services in Lucknow. Our Developers have the good knowledge and skillsets required
                            for application development.
                        </p>
                        <div class="row">
                            <div class="col-md-3 col-lg-3">
                                <img src="~/afluexit/images/services/budget.png" class="img-fluid pt-4" alt="software-devlopment" />
                                <div class="budget_development mt-2">
                                    <p>BUDGET FRIENDLY SOFTWARE DEVELOPMENT</p>
                                </div>
                            </div>
                            <div class="col-md-3 col-lg-3">
                                <img src="~/afluexit/images/services/talented.png" class="img-fluid pt-4" alt="software-devlopment" />
                                <div class="budget_development mt-2">
                                    <p>TALENTED DEVELOPERS</p>
                                </div>
                            </div>
                            <div class="col-md-3 col-lg-3">
                                <img src="~/afluexit/images/services/profitability.png" class="img-fluid pt-4" alt="software-devlopment" />
                                <div class="budget_development mt-2">
                                    <p>PROFITABILITY</p>
                                </div>
                            </div>
                            <div class="col-md-3 col-lg-3">
                                <img src="~/afluexit/images/services/customer_dedline.png" class="img-fluid pt-4" alt="software-devlopment" />
                                <div class="budget_development mt-2">
                                    <p>MEET CUSTOMER DEADLINES</p>
                                </div>
                            </div>
                        </div>
                        <h5 class="green">Our Software Development Process</h5>
                        <p class="text-justify">As a professional Application Development Company in Lucknow, our Software DevelopmentProcess is a systematic approach, towards delivering a quality end product. Our process begins with,</p>
                        <img src="~/afluexit/images/services/infographic_image.jpg" class="img-fluid pt-4" alt="software-devlopment" />
                        <div class="row">
                            <div class="col-md-7 col-lg-7 col-sm-12">
                                <h5 class="green pt-4">Looking For a Quality and Affordable Services</h5>
                                <p class="text-justify">
                                    We help you to achieve faster and better IT Services for your business. We’re a team of programmers, makers, thinkers, explorers, creators. We’re serious about delivering great outcomes, with and quality and affordable
                                    prices. The Afluex team works hard to meet the market necessities more intensely to deliver the best solutions to satisfy the client.
                                </p>
                            </div>
                            <div class="col-md-5 col-lg-5 col-sm-12">
                                <img src="~/afluexit/images/services/system-integration.png" class="img-fluid" alt="System Integration" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Video Column -->
            <div class="col-xl-4 col-lg-4 col-md-4 col-sm-12">
                <div class="services_inner_column">
                    <div class="ser_title">
                        <span class="title">Enquiry Here</span>
                        <h2>For Quick Demo</h2>
                    </div>
                  @{Html.RenderAction("DemoContact", "web", new { area = "" });}
                </div>
            </div>
        </div>
    </div>
</section>